name: Deploy Multilingual Site

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages

    - name: Create versioned directory
      run: |
        mkdir -p v${{ github.event.release.tag }}
        cp -r ./public/* ./v${{ github.event.release.tag }}/
